### ISSUE TITLE
[VSCode]"Message header must separate key and value using :: Error: Message header must separate key and value using :"

### ISSUE THREAD

**Issue by apupier** [lhein/camel-language-server#71]
occurred after few completions but cannot reproduce for now.

```
[apache-camel.vscode-apache-camel] Message header must separate key and value using :: Error: Message header must separate key and value using :
	at C:\Users\Aurelien Pupier\.vscode\extensions\apache-camel.vscode-apache-camel-0.0.1\node_modules\vscode-jsonrpc\lib\messageReader.js:61:23
	at Array.forEach (native)
	at MessageBuffer.tryReadHeaders (C:\Users\Aurelien Pupier\.vscode\extensions\apache-camel.vscode-apache-camel-0.0.1\node_modules\vscode-jsonrpc\lib\messageReader.js:58:17)
	at StreamMessageReader.onData (C:\Users\Aurelien Pupier\.vscode\extensions\apache-camel.vscode-apache-camel-0.0.1\node_modules\vscode-jsonrpc\lib\messageReader.js:173:43)
	at Socket.<anonymous> (C:\Users\Aurelien Pupier\.vscode\extensions\apache-camel.vscode-apache-camel-0.0.1\node_modules\vscode-jsonrpc\lib\messageReader.js:164:19)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by apupier** [comment]
steps to reproduce:
 <from uri="ahc-wss:httpUri?binding=aa">
type a & after the aa

**Comment by apupier** [comment]
this error is due to the fact that when parsing the xml, there is a parse exception thrown and logged. Seems VSCode is less permissive when something arrives on stdin/stdout

**Comment by apupier** [comment]
```
ERROR [main] (HoverProcessor.java:52) - Error searching hover
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 34; The entity name must immediately follow the '&' in the entity reference.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.apache.camel.tools.lsp.internal.parser.ParserFileHelper.hasElementFromCamelNamespace(ParserFileHelper.java:90)
	at org.apache.camel.tools.lsp.internal.parser.ParserFileHelper.getCorrespondingCamelNodeForCompletion(ParserFileHelper.java:78)
	at org.apache.camel.tools.lsp.internal.hover.HoverProcessor.getHover(HoverProcessor.java:44)
	at org.apache.camel.tools.lsp.internal.CamelTextDocumentService.hover(CamelTextDocumentService.java:94)
	at org.apache.camel.tools.lsp.internal.hover.CamelLanguageServerHoverTest.testDontProvideDocumentationOnHoverWhenEdnginWWithAnd(CamelLanguageServerHoverTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
```

**Comment by apupier** [comment]
there is no more this error. There is "just" no completion in case of '&' and not &amp;
