### ISSUE TITLE
[VSCode]debug console error: "Received message which is neither a response nor a notification message"

### ISSUE THREAD

**Issue by apupier** [lhein/camel-language-server#73]
```
Received message which is neither a response nor a notification message:
{
    "jsonrpc": "2.0",
    "id": "9"
}
```

```
[Error - 2:18:22 PM] Request textDocument/hover failed.
Error: The received response has neither a result nor an error property.
	at handleInvalidMessage (c:\git\camel-language-server\clients\vscode\node_modules\vscode-jsonrpc\lib\main.js:511:40)
	at processMessageQueue (c:\git\camel-language-server\clients\vscode\node_modules\vscode-jsonrpc\lib\main.js:261:17)
	at Immediate.<anonymous> (c:\git\camel-language-server\clients\vscode\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
[Error - 2:18:23 PM] Request textDocument/hover failed.
Error: The received response has neither a result nor an error property.
	at handleInvalidMessage (c:\git\camel-language-server\clients\vscode\node_modules\vscode-jsonrpc\lib\main.js:511:40)
	at processMessageQueue (c:\git\camel-language-server\clients\vscode\node_modules\vscode-jsonrpc\lib\main.js:261:17)
	at Immediate.<anonymous> (c:\git\camel-language-server\clients\vscode\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by apupier** [comment]
fixed by https://github.com/lhein/camel-language-server/pull/74/commits/37ff85b41755fa1dbdd06cfbfcbe830c38403d8a

the issue was that the specification has changed from need to support null or not and the VS Code client is still not supporting it
